### ISSUE TITLE
Usage section in README.md

### ISSUE THREAD

**Issue by peter279k** [fillips/php-config#1]
As title, I think we need to add the usage section in `README`?

@filips123, do you have any idea about this?

Thanks.

**Comment by filips123** [comment]
Package is currently not finished. That's why readme is not finished. I will publish it soon.

**Comment by filips123** [comment]
I created new version and readme. Feel free to download and test. 😊

There are currently some problems with custom options in writer, but I will try to fix this. The problem is that when user choose to not use trailing comma in array, the commas will be missing. The code could also be better quality.
If you have time, you can fix this and submit PR. Thanks!
